# Generated by Django 3.2.4 on 2021-07-02 17:35

import car.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('modelId', models.IntegerField(primary_key=True, serialize=False)),
                ('modelName', models.CharField(default='Maruti Suzuki Swift', max_length=128)),
                ('modelYear', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), car.models.max_value_current_year])),
                ('modelType', models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Luxury', 'Luxury')], default=('Hatchback', 'Hatchback'), max_length=128)),
                ('modelImg', models.ImageField(upload_to='media')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('subject', models.CharField(max_length=128)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('notes', models.TextField(editable=False)),
                ('rating', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateNo', models.CharField(max_length=10, unique=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Available'), (1, 'Booked'), (2, 'Maintainance')])),
                ('modelId', models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='car.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('securityProof', models.CharField(max_length=12, unique=True)),
                ('depositAmount', models.DecimalField(decimal_places=2, default=2499, editable=False, max_digits=5)),
                ('isDepositPaid', models.BooleanField()),
                ('pickupDate', models.DateTimeField()),
                ('dropDate', models.DateTimeField()),
                ('bookingDate', models.DateField(auto_now_add=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
