# Generated by Django 3.2.4 on 2021-07-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20210629_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carType', models.CharField(max_length=128)),
                ('plateNo', models.CharField(max_length=8)),
                ('carImg', models.ImageField(upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2)])),
            ],
        ),
    ]
