# Generated by Django 3.2.4 on 2021-07-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_fleet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='plateNo',
            field=models.CharField(max_length=10),
        ),
    ]
