# Generated by Django 3.2.4 on 2021-07-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_contact_isresolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='notes',
            field=models.TextField(),
        ),
    ]
