# Generated by Django 3.2.4 on 2021-07-02 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_alter_testimonials_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
