# Generated by Django 3.2.4 on 2021-07-02 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_alter_testimonials_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='rating',
            field=models.IntegerField(default=5, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
