# Generated by Django 3.2.4 on 2021-07-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_alter_testimonials_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pickupLocation',
            field=models.CharField(choices=[('Ahmedabad', (('railwaystation', 'Railway Station'), ('airport', 'Airport')))], default='railway', max_length=128),
        ),
        migrations.AlterField(
            model_name='contact',
            name='notes',
            field=models.TextField(),
        ),
    ]
