# Generated by Django 3.2.4 on 2021-07-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_alter_fleet_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
