# Generated by Django 3.2.4 on 2021-07-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_testimonials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonials',
            new_name='Testimonial',
        ),
    ]
