# Generated by Django 3.2.4 on 2021-07-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_auto_20210709_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dropLocation',
            field=models.CharField(choices=[('Ahmedabad', (('ahmrailway', 'Railway Station'), ('ahmairport', 'Ahmedabad Airport')))], default='ahmrailway', max_length=128),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickupLocation',
            field=models.CharField(choices=[('Ahmedabad', (('ahmrailway', 'Railway Station'), ('ahmairport', 'Ahmedabad Airport')))], default='ahmrailway', max_length=128),
        ),
    ]
