# Generated by Django 3.2.4 on 2021-07-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_rename_testimonials_testimonial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonial',
            new_name='Testimonials',
        ),
    ]
