# Generated by Django 3.2.4 on 2021-07-09 04:55

from django.db import migrations, models
import django.utils.timezone
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_alter_booking_depositamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='securityProof',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=256)),
        ),
    ]
