# Generated by Django 3.2.4 on 2021-07-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_rename_testimonial_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='rating',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
