# Generated by Django 3.2.4 on 2021-07-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_auto_20210709_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bookingDate',
        ),
        migrations.AlterField(
            model_name='booking',
            name='dropDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickupDate',
            field=models.DateField(),
        ),
    ]
