# Generated by Django 3.2.4 on 2021-07-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_auto_20210709_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='depositAmount',
            field=models.DecimalField(decimal_places=2, default=2499, max_digits=6),
        ),
        migrations.AlterField(
            model_name='booking',
            name='isDepositPaid',
            field=models.BooleanField(default=False),
        ),
    ]
