# Generated by Django 3.2.4 on 2021-07-01 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0013_alter_testimonials_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('securityProof', models.CharField(max_length=12, unique=True)),
                ('depositAmount', models.DecimalField(decimal_places=2, default=2499, max_digits=5)),
                ('isDepositPaid', models.BooleanField()),
                ('pickupDate', models.DateTimeField()),
                ('dropDate', models.DateTimeField()),
                ('bookingDate', models.DateField(auto_now_add=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
