# Generated by Django 3.2.4 on 2021-07-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_auto_20210709_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='carId',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='car.fleet'),
            preserve_default=False,
        ),
    ]
