# Generated by Django 3.2.4 on 2021-07-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0016_auto_20210709_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='grossAmount',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='status',
            field=models.SmallIntegerField(choices=[('available', 'Available'), ('booked', 'Booked'), ('maintainance', 'Maintainance')]),
        ),
    ]
