# Generated by Django 3.2.4 on 2021-07-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0017_auto_20210709_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Available'), (1, 'Booked'), (2, 'Maintainance')]),
        ),
    ]
