# Generated by Django 3.2.4 on 2021-07-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0018_alter_fleet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='grossAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='totalAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
