# Generated by Django 3.2.4 on 2021-07-09 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0019_auto_20210709_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='carId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.fleet'),
        ),
    ]
