# Generated by Django 3.2.4 on 2021-07-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0020_alter_booking_carid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='isDepositPaid',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('saved', 'Saved'), ('paid', 'Paid'), ('done', 'Done')], default='paid', max_length=64),
            preserve_default=False,
        ),
    ]
