# Generated by Django 3.2.4 on 2021-07-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0021_auto_20210710_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='depositAmount',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='name',
        ),
        migrations.AddField(
            model_name='testimonials',
            name='username',
            field=models.CharField(default='Test', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='notes',
            field=models.TextField(),
        ),
    ]
