# Generated by Django 3.2.4 on 2021-07-10 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0022_auto_20210710_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonials',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='modelYear',
        ),
    ]
