# Generated by Django 3.2.4 on 2021-07-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0023_auto_20210710_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='rating',
        ),
        migrations.AlterField(
            model_name='booking',
            name='dropLocation',
            field=models.CharField(choices=[('Ahmedabad', (('ahmrailway', 'Ahmedabad Railway Station'), ('ahmairport', 'Ahmedabad Airport'))), ('Mumbai', (('mumrail', 'Mumbai Railway Statin'), ('mumairport', 'Mumbai Airport')))], max_length=128),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickupLocation',
            field=models.CharField(choices=[('Ahmedabad', (('ahmrailway', 'Ahmedabad Railway Station'), ('ahmairport', 'Ahmedabad Airport'))), ('Mumbai', (('mumrail', 'Mumbai Railway Statin'), ('mumairport', 'Mumbai Airport')))], max_length=128),
        ),
    ]
