# Generated by Django 3.2.4 on 2021-07-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0024_auto_20210716_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='name',
            field=models.CharField(help_text='This name will be displayed in your testimonial.', max_length=512),
        ),
    ]
